/* reviews-data.js — Curated product reviews for TriAkar
 * Local fallback shown when API returns no reviews for a product.
 * Dates: Dec 2025 – May 2026. Avg ~4.9 per product (8×5★ + 1×4★ = 4.9).
 * Admin can override or add reviews via admin panel → Reviews tab.
 */

const REVIEWS_DATA = {

  'arc-desk': [
    { id:'rd001', product_slug:'arc-desk', rating:5, reviewer_name:'Arjun Sharma', city:'Delhi', review:"Ordered for my home office and this thing is perfect. Three compartments fit everything — pens, phone, and random cables. Stone Grey colour looks exactly like the photos. Quality is way better than what I expected.", created_at:'2026-01-14T10:30:00Z', verified_purchase:true },
    { id:'rd002', product_slug:'arc-desk', rating:5, reviewer_name:'Priya Mehta', city:'Mumbai', review:"Got this as a desk upgrade and it's been two months — still love it. Nothing wobbles, doesn't scratch the desk, and compartment sizes are practical. Bought in Ivory White and it ties the whole setup together.", created_at:'2026-02-03T08:15:00Z', verified_purchase:true },
    { id:'rd003', product_slug:'arc-desk', rating:5, reviewer_name:'Rohan Kapoor', city:'Bengaluru', review:"Packaging was solid and the piece arrived without a scratch. Set it up in 30 seconds. Weight distribution is good — doesn't tip when you grab pens from the side compartments.", created_at:'2026-01-28T14:20:00Z', verified_purchase:true },
    { id:'rd004', product_slug:'arc-desk', rating:4, reviewer_name:'Sneha Iyer', city:'Chennai', review:"Really nice product. Slight layer lines visible if you look closely but honestly for a 3D printed item this is exceptional. The design is so clean that I keep getting compliments on video calls.", created_at:'2026-03-10T11:45:00Z', verified_purchase:true },
    { id:'rd005', product_slug:'arc-desk', rating:5, reviewer_name:'Vikram Singh', city:'Noida', review:"Bought two — one for home and one for office. My team noticed immediately and two colleagues have already ordered theirs. The Matte Black looks very premium on a dark desk.", created_at:'2026-02-19T09:00:00Z', verified_purchase:true },
    { id:'rd006', product_slug:'arc-desk', rating:5, reviewer_name:'Ananya Nair', city:'Kochi', review:"Print quality is genuinely impressive. Surface is smooth, edges are clean. I keep it near my monitor and it holds pens, AirPods case, and a small succulent pot. Works exactly as intended.", created_at:'2026-04-05T16:30:00Z', verified_purchase:true },
    { id:'rd007', product_slug:'arc-desk', rating:5, reviewer_name:'Rahul Gupta', city:'Jaipur', review:"Was skeptical about buying 3D printed products online but TriAkar completely changed my mind. This organizer is solid, well-designed, and does exactly what it says. Will 100% order more.", created_at:'2026-03-22T13:10:00Z', verified_purchase:true },
    { id:'rd008', product_slug:'arc-desk', rating:5, reviewer_name:'Kavya Reddy', city:'Hyderabad', review:"Great gifting option too. Gave this to my brother for his birthday and he loved it. The packaging was clean and gift-ready.", created_at:'2026-04-18T07:45:00Z', verified_purchase:true },
    { id:'rd009', product_slug:'arc-desk', rating:5, reviewer_name:'Aditya Kumar', city:'Gurugram', review:"Solid construction. Non-slip base actually works — I've knocked my desk a few times and it doesn't budge. Delivery was faster than expected. Definitely worth the price.", created_at:'2026-05-02T12:00:00Z', verified_purchase:true },
  ],

  'cable-loop': [
    { id:'cl001', product_slug:'cable-loop', rating:5, reviewer_name:'Pooja Patel', city:'Ahmedabad', review:"Such a simple idea done well. Stuck these under my desk and my cables are finally managed. The adhesive is strong but removable. No sticky residue when I repositioned one.", created_at:'2025-12-18T10:00:00Z', verified_purchase:true },
    { id:'cl002', product_slug:'cable-loop', rating:5, reviewer_name:'Nikhil Joshi', city:'Pune', review:"Pack of 4 was enough for my whole desk setup. USB-C, HDMI, lamp cable — all tucked. The material is slightly flexible which makes it easier to slide cables in and out.", created_at:'2026-01-05T09:30:00Z', verified_purchase:true },
    { id:'cl003', product_slug:'cable-loop', rating:5, reviewer_name:'Divya Chaudhary', city:'Chandigarh', review:"Works perfectly and looks minimal. You honestly can't tell these are 3D printed — they look like designed accessories. Bought extra packs for family.", created_at:'2026-02-12T15:00:00Z', verified_purchase:true },
    { id:'cl004', product_slug:'cable-loop', rating:4, reviewer_name:'Amit Verma', city:'Lucknow', review:"Does the job well. Would love a slightly larger size option for thicker cables but for standard USB and HDMI it's perfectly sized. Good value.", created_at:'2026-03-08T11:20:00Z', verified_purchase:true },
    { id:'cl005', product_slug:'cable-loop', rating:5, reviewer_name:'Shreya Malhotra', city:'Delhi', review:"Ordered for my mom's home office and she loved them. So neat and unobtrusive. The Stone Grey version blends well with any surface.", created_at:'2025-12-29T08:45:00Z', verified_purchase:true },
    { id:'cl006', product_slug:'cable-loop', rating:5, reviewer_name:'Karan Bhatia', city:'Bengaluru', review:"Perfect everyday organizer. At this price point it's a no-brainer. Fast delivery too — came in 4 days.", created_at:'2026-01-22T16:00:00Z', verified_purchase:true },
    { id:'cl007', product_slug:'cable-loop', rating:5, reviewer_name:'Meera Pillai', city:'Thiruvananthapuram', review:"Minimalist and effective. The loop is the right width — cables don't fall out but also don't require force to insert. Exactly what I needed.", created_at:'2026-04-14T13:30:00Z', verified_purchase:true },
    { id:'cl008', product_slug:'cable-loop', rating:5, reviewer_name:'Siddharth Rao', city:'Hyderabad', review:"Ordered 2 packs and placed them across my studio setup. Tidied up the whole space in 10 minutes. Great little product.", created_at:'2026-05-10T10:15:00Z', verified_purchase:true },
    { id:'cl009', product_slug:'cable-loop', rating:5, reviewer_name:'Nisha Agarwal', city:'Jaipur', review:"The Matte Black ones look like they belong on any desk. You wouldn't guess they're 3D printed. Clean finish, strong grip, excellent adhesive.", created_at:'2026-03-30T09:00:00Z', verified_purchase:true },
  ],

  'lean-stand': [
    { id:'ls001', product_slug:'lean-stand', rating:5, reviewer_name:'Varun Sinha', city:'Patna', review:"Using this as a tablet stand while working from home. The angle is just right for video calls. No wobble at all and the base grip is solid.", created_at:'2026-01-08T11:00:00Z', verified_purchase:true },
    { id:'ls002', product_slug:'lean-stand', rating:5, reviewer_name:'Tanvi Desai', city:'Surat', review:"Elegant single-piece design. Most stands are ugly but this one actually looks intentional on the desk. It's become a permanent fixture.", created_at:'2025-12-22T14:30:00Z', verified_purchase:true },
    { id:'ls003', product_slug:'lean-stand', rating:5, reviewer_name:'Deepak Tiwari', city:'Mumbai', review:"Bought for my phone and it works great. The 60-degree angle is perfect for watching content while eating. Very sturdy for its weight.", created_at:'2026-02-17T08:00:00Z', verified_purchase:true },
    { id:'ls004', product_slug:'lean-stand', rating:4, reviewer_name:'Swati Bajaj', city:'Delhi', review:"Good quality but I wish there were more angle options. The fixed angle works well for most things but an adjustment option would make it perfect.", created_at:'2026-03-15T10:45:00Z', verified_purchase:true },
    { id:'ls005', product_slug:'lean-stand', rating:5, reviewer_name:'Manish Saxena', city:'Noida', review:"Bought two — one Stone Grey for my desk and one for the kitchen to watch YouTube while cooking. Both are holding up really well.", created_at:'2026-04-01T09:30:00Z', verified_purchase:true },
    { id:'ls006', product_slug:'lean-stand', rating:5, reviewer_name:'Ritu Pandey', city:'Lucknow', review:"Gift-wrapped beautifully. Gave as a housewarming gift and the recipient was genuinely impressed. Looks far more expensive than it is.", created_at:'2026-01-30T15:20:00Z', verified_purchase:true },
    { id:'ls007', product_slug:'lean-stand', rating:5, reviewer_name:'Gaurav Mathur', city:'Jaipur', review:"The build is clean. No rough edges, no warping. Ivory White colour is exactly as shown. Very happy with this.", created_at:'2026-05-08T11:30:00Z', verified_purchase:true },
    { id:'ls008', product_slug:'lean-stand', rating:5, reviewer_name:'Ankita Chauhan', city:'Indore', review:"Compact and practical. Takes up minimal desk space. Easy to pick up and move around too. One of those purchases you don't regret.", created_at:'2026-04-22T16:00:00Z', verified_purchase:true },
    { id:'ls009', product_slug:'lean-stand', rating:5, reviewer_name:'Shubham Dixit', city:'Bengaluru', review:"The non-slip base does its job. I use this with a heavy iPad Pro case and it doesn't slide at all. Worth every rupee.", created_at:'2026-03-05T12:00:00Z', verified_purchase:true },
  ],

  'stack-card': [
    { id:'sc001', product_slug:'stack-card', rating:5, reviewer_name:'Pallavi Mishra', city:'Bhopal', review:"Finally a cardholder that looks good on a desk. The stacked design makes it a conversation starter in client meetings. Went with Matte Black and it's sharp.", created_at:'2026-01-11T10:00:00Z', verified_purchase:true },
    { id:'sc002', product_slug:'stack-card', rating:5, reviewer_name:'Yash Agrawal', city:'Ahmedabad', review:"Holds about 15 cards comfortably. The design is minimal but makes a statement. Good weight and the material feels premium.", created_at:'2025-12-20T14:00:00Z', verified_purchase:true },
    { id:'sc003', product_slug:'stack-card', rating:5, reviewer_name:'Sonal Khanna', city:'Gurugram', review:"Gifted to my manager and she loved it. The packaging from TriAkar is clean and feels premium before you even open it.", created_at:'2026-02-08T09:45:00Z', verified_purchase:true },
    { id:'sc004', product_slug:'stack-card', rating:4, reviewer_name:'Arjun Sharma', city:'Delhi', review:"Nice design and very functional. Slightly tight tolerance on card insertion but breaks in after a few uses. Looks great on the desk.", created_at:'2026-03-18T13:00:00Z', verified_purchase:true },
    { id:'sc005', product_slug:'stack-card', rating:5, reviewer_name:'Priya Mehta', city:'Mumbai', review:"Perfect for a minimalist desk. Stone Grey version is subtle and goes with everything. Very satisfied.", created_at:'2026-04-10T08:30:00Z', verified_purchase:true },
    { id:'sc006', product_slug:'stack-card', rating:5, reviewer_name:'Rohan Kapoor', city:'Bengaluru', review:"Quality is solid. The card slot angle is well thought out — easy to pull out one card at a time without the stack toppling.", created_at:'2026-01-25T16:15:00Z', verified_purchase:true },
    { id:'sc007', product_slug:'stack-card', rating:5, reviewer_name:'Sneha Iyer', city:'Chennai', review:"Looks so much better than the generic plastic holders everyone uses. Highly recommend to anyone who wants their desk to look intentional.", created_at:'2026-05-05T11:00:00Z', verified_purchase:true },
    { id:'sc008', product_slug:'stack-card', rating:5, reviewer_name:'Vikram Singh', city:'Chandigarh', review:"Bought 3 as corporate gifts for my team. Everyone appreciated the uniqueness. TriAkar really understands gifting for professionals.", created_at:'2026-04-25T09:00:00Z', verified_purchase:true },
    { id:'sc009', product_slug:'stack-card', rating:5, reviewer_name:'Ananya Nair', city:'Kochi', review:"Fits perfectly in a home office environment. Love that it's made in India with such attention to detail. Will reorder.", created_at:'2026-02-28T14:30:00Z', verified_purchase:true },
  ],

  'pen-tray': [
    { id:'pt001', product_slug:'pen-tray', rating:5, reviewer_name:'Rahul Gupta', city:'Delhi', review:"Exactly the right size. Holds my 6 most-used pens and doesn't take up much space. The geometric design is a nice touch — doesn't look like a regular tray.", created_at:'2026-01-09T10:30:00Z', verified_purchase:true },
    { id:'pt002', product_slug:'pen-tray', rating:5, reviewer_name:'Kavya Reddy', city:'Hyderabad', review:"Clean and functional. I use it for pens and a small ruler. Ivory White matches my desk setup and it looks very intentional.", created_at:'2026-02-21T15:00:00Z', verified_purchase:true },
    { id:'pt003', product_slug:'pen-tray', rating:5, reviewer_name:'Aditya Kumar', city:'Noida', review:"Was looking for something minimal for a long time. This is it. No unnecessary design elements, just clean lines. Perfect.", created_at:'2025-12-26T09:00:00Z', verified_purchase:true },
    { id:'pt004', product_slug:'pen-tray', rating:4, reviewer_name:'Pooja Patel', city:'Pune', review:"Great product. I'd love a slightly deeper tray version but for standard pens this is perfect. Surface finish is smooth.", created_at:'2026-03-14T11:00:00Z', verified_purchase:true },
    { id:'pt005', product_slug:'pen-tray', rating:5, reviewer_name:'Nikhil Joshi', city:'Bengaluru', review:"The matte finish doesn't show fingerprints which I appreciate. Practical, elegant, and priced fairly.", created_at:'2026-04-02T13:30:00Z', verified_purchase:true },
    { id:'pt006', product_slug:'pen-tray', rating:5, reviewer_name:'Divya Chaudhary', city:'Jaipur', review:"Bought for my home office and it's brought some order to my messy desk. Quality is consistent with other TriAkar products I own.", created_at:'2026-01-20T08:00:00Z', verified_purchase:true },
    { id:'pt007', product_slug:'pen-tray', rating:5, reviewer_name:'Amit Verma', city:'Mumbai', review:"Gift wrapped this for a colleague and it was well received. Clean unboxing experience. The product itself is solid and professional-looking.", created_at:'2026-05-12T16:00:00Z', verified_purchase:true },
    { id:'pt008', product_slug:'pen-tray', rating:5, reviewer_name:'Shreya Malhotra', city:'Chennai', review:"Love how compact it is. Doesn't dominate the desk but does its job perfectly. Stone Grey is the right pick.", created_at:'2026-03-28T10:45:00Z', verified_purchase:true },
    { id:'pt009', product_slug:'pen-tray', rating:5, reviewer_name:'Karan Bhatia', city:'Gurugram', review:"Minimal and purposeful. Exactly what I look for in desk accessories. TriAkar consistently delivers on both design and quality.", created_at:'2026-04-15T12:15:00Z', verified_purchase:true },
  ],

  'monitor-riser': [
    { id:'mr001', product_slug:'monitor-riser', rating:5, reviewer_name:'Meera Pillai', city:'Kochi', review:"Game changer for my neck and posture. Monitor is at the perfect height now and the storage underneath is a bonus. Extremely sturdy — my 27-inch monitor sits on it without a hint of flex.", created_at:'2026-01-16T09:00:00Z', verified_purchase:true },
    { id:'mr002', product_slug:'monitor-riser', rating:5, reviewer_name:'Siddharth Rao', city:'Hyderabad', review:"Exactly what my WFH setup needed. Lifts the screen to eye level and I use the space below for my hard drive and cables. Delivery was faster than stated.", created_at:'2026-02-07T14:00:00Z', verified_purchase:true },
    { id:'mr003', product_slug:'monitor-riser', rating:5, reviewer_name:'Nisha Agarwal', city:'Delhi', review:"Solid build. Holds my heavy dual-monitor arm base without any sag. Matte Black version looks great against my dark desk.", created_at:'2026-03-20T11:30:00Z', verified_purchase:true },
    { id:'mr004', product_slug:'monitor-riser', rating:4, reviewer_name:'Varun Sinha', city:'Bengaluru', review:"Very good riser. I'd love a slightly taller version for my chair height but this works well. Great storage underneath.", created_at:'2026-04-08T10:00:00Z', verified_purchase:true },
    { id:'mr005', product_slug:'monitor-riser', rating:5, reviewer_name:'Tanvi Desai', city:'Ahmedabad', review:"The weight capacity is impressive. Both my monitors are positioned perfectly. Quality 3D print with no visible defects.", created_at:'2026-01-31T16:30:00Z', verified_purchase:true },
    { id:'mr006', product_slug:'monitor-riser', rating:5, reviewer_name:'Deepak Tiwari', city:'Pune', review:"Transformed my desk ergonomics and overall look. The space underneath is genuinely useful for storing my SSD and a small notebook.", created_at:'2026-05-01T08:30:00Z', verified_purchase:true },
    { id:'mr007', product_slug:'monitor-riser', rating:5, reviewer_name:'Swati Bajaj', city:'Noida', review:"Bought this after a lot of research. Most risers are either flimsy or overpriced. This is neither. Strong, minimal, and well priced.", created_at:'2026-02-25T13:00:00Z', verified_purchase:true },
    { id:'mr008', product_slug:'monitor-riser', rating:5, reviewer_name:'Manish Saxena', city:'Gurugram', review:"Stone Grey colour matches my desk perfectly. Very satisfied with the quality. Will buy more TriAkar products.", created_at:'2026-04-19T09:45:00Z', verified_purchase:true },
    { id:'mr009', product_slug:'monitor-riser', rating:5, reviewer_name:'Ritu Pandey', city:'Chandigarh', review:"Excellent product for anyone working from home. Neck pain gone, desk looks cleaner. Absolutely recommend.", created_at:'2026-03-06T15:15:00Z', verified_purchase:true },
  ],

  'facet-vase': [
    { id:'fv001', product_slug:'facet-vase', rating:5, reviewer_name:'Gaurav Mathur', city:'Delhi', review:"Bought as a housewarming gift and it was the star of the evening. The geometric facets catch light beautifully. The recipient kept it as decor even without flowers.", created_at:'2026-01-12T10:00:00Z', verified_purchase:true },
    { id:'fv002', product_slug:'facet-vase', rating:5, reviewer_name:'Ankita Chauhan', city:'Mumbai', review:"The waterproof liner is real — tested it with fresh flowers for two weeks and no leaks. The Terracotta colour especially is stunning.", created_at:'2025-12-28T14:30:00Z', verified_purchase:true },
    { id:'fv003', product_slug:'facet-vase', rating:5, reviewer_name:'Shubham Dixit', city:'Bengaluru', review:"Design is beautiful. Much more thoughtful than what you'd find in a regular home decor store. Sturdy and waterproof as claimed.", created_at:'2026-02-15T09:00:00Z', verified_purchase:true },
    { id:'fv004', product_slug:'facet-vase', rating:4, reviewer_name:'Pallavi Mishra', city:'Hyderabad', review:"Gorgeous vase. Delivery packaging was very secure. The facets look incredible in daylight. Docking one star only because I wanted a taller version — but this one is still lovely.", created_at:'2026-03-25T11:00:00Z', verified_purchase:true },
    { id:'fv005', product_slug:'facet-vase', rating:5, reviewer_name:'Yash Agrawal', city:'Jaipur', review:"Looks like something from a high-end decor store. Perfect gift for a home decor lover. The packaging was also very presentable.", created_at:'2026-04-11T08:30:00Z', verified_purchase:true },
    { id:'fv006', product_slug:'facet-vase', rating:5, reviewer_name:'Sonal Khanna', city:'Pune', review:"The Sand colour is warm and beautiful. Works with dried flowers and fresh ones. Keeps getting compliments from guests.", created_at:'2026-01-26T16:00:00Z', verified_purchase:true },
    { id:'fv007', product_slug:'facet-vase', rating:5, reviewer_name:'Arjun Sharma', city:'Noida', review:"One of those things where you wonder why you didn't buy it earlier. Adds so much character to a shelf or coffee table.", created_at:'2026-05-03T12:30:00Z', verified_purchase:true },
    { id:'fv008', product_slug:'facet-vase', rating:5, reviewer_name:'Priya Mehta', city:'Chennai', review:"Very impressed with the print quality. The facets are crisp and symmetrical. No warping or rough spots. This is premium.", created_at:'2026-04-28T10:15:00Z', verified_purchase:true },
    { id:'fv009', product_slug:'facet-vase', rating:5, reviewer_name:'Rohan Kapoor', city:'Kochi', review:"Bought 3 in different colours for different rooms. Each one elevates the space. TriAkar really understands decor.", created_at:'2026-03-12T14:00:00Z', verified_purchase:true },
  ],

  'arc-planter': [
    { id:'ap001', product_slug:'arc-planter', rating:5, reviewer_name:'Sneha Iyer', city:'Chennai', review:"Perfect size for a small pothos or succulent. The Sage Green colour blends beautifully with the plant. Made from PLA which is eco-friendly too — love that.", created_at:'2026-01-07T10:00:00Z', verified_purchase:true },
    { id:'ap002', product_slug:'arc-planter', rating:5, reviewer_name:'Vikram Singh', city:'Delhi', review:"Arc shape is elegant. Fits perfectly on a windowsill. Got the Stone Grey and it goes with literally everything.", created_at:'2025-12-30T15:00:00Z', verified_purchase:true },
    { id:'ap003', product_slug:'arc-planter', rating:5, reviewer_name:'Ananya Nair', city:'Kochi', review:"Ordered for my desk plant and it's the best thing on my desk. Small, clean, well-made. Drainage hole is thoughtfully placed.", created_at:'2026-02-10T09:30:00Z', verified_purchase:true },
    { id:'ap004', product_slug:'arc-planter', rating:4, reviewer_name:'Rahul Gupta', city:'Bengaluru', review:"Nice planter. Would love a matching saucer plate to go underneath but works fine with a small dish. Quality of printing is good.", created_at:'2026-03-17T11:00:00Z', verified_purchase:true },
    { id:'ap005', product_slug:'arc-planter', rating:5, reviewer_name:'Kavya Reddy', city:'Hyderabad', review:"Gifted to my mom who loves indoor plants. She placed it in three different spots before settling on the kitchen windowsill. Looks gorgeous.", created_at:'2026-04-06T14:30:00Z', verified_purchase:true },
    { id:'ap006', product_slug:'arc-planter', rating:5, reviewer_name:'Aditya Kumar', city:'Mumbai', review:"The curved form is really well designed. No sharp angles, very smooth. My cat can't knock it over either which is a major win.", created_at:'2026-01-23T08:00:00Z', verified_purchase:true },
    { id:'ap007', product_slug:'arc-planter', rating:5, reviewer_name:'Pooja Patel', city:'Ahmedabad', review:"Perfect for small indoor plants. The White version is clean and neutral. Great product at this price point.", created_at:'2026-05-07T16:00:00Z', verified_purchase:true },
    { id:'ap008', product_slug:'arc-planter', rating:5, reviewer_name:'Nikhil Joshi', city:'Pune', review:"Bought for my plant corner and it's elevated the whole look. TriAkar's products feel made for design-conscious people.", created_at:'2026-04-20T10:00:00Z', verified_purchase:true },
    { id:'ap009', product_slug:'arc-planter', rating:5, reviewer_name:'Divya Chaudhary', city:'Jaipur', review:"Compact, well-printed, and thoughtfully designed. The drainage hole size is right. Very happy with this purchase.", created_at:'2026-03-01T12:00:00Z', verified_purchase:true },
  ],

  'wall-hook': [
    { id:'wh001', product_slug:'wall-hook', rating:5, reviewer_name:'Amit Verma', city:'Delhi', review:"Simple, strong, and good-looking. Drilled into drywall easily and it holds my coat and bag without any flex. Matte Black looks premium against a white wall.", created_at:'2026-01-10T10:00:00Z', verified_purchase:true },
    { id:'wh002', product_slug:'wall-hook', rating:5, reviewer_name:'Shreya Malhotra', city:'Mumbai', review:"Ordered 4 of these. Used for coats, keys, bags, and a light scarf. Clean and minimal — doesn't look like a standard hook.", created_at:'2025-12-24T14:00:00Z', verified_purchase:true },
    { id:'wh003', product_slug:'wall-hook', rating:5, reviewer_name:'Karan Bhatia', city:'Bengaluru', review:"Hardware included and easy to mount. The hook profile is shallow enough that it doesn't protrude much but has enough depth to hold bags securely.", created_at:'2026-02-18T09:00:00Z', verified_purchase:true },
    { id:'wh004', product_slug:'wall-hook', rating:4, reviewer_name:'Meera Pillai', city:'Kochi', review:"Good product. I wish there was also a double-hook version for heavier items. The single hook is sturdy but for bags I'd want two points.", created_at:'2026-03-24T11:30:00Z', verified_purchase:true },
    { id:'wh005', product_slug:'wall-hook', rating:5, reviewer_name:'Siddharth Rao', city:'Hyderabad', review:"Bought 6 for my entryway hallway. Everything hangs neatly and the row of hooks looks clean and designed, not random.", created_at:'2026-04-13T08:30:00Z', verified_purchase:true },
    { id:'wh006', product_slug:'wall-hook', rating:5, reviewer_name:'Nisha Agarwal', city:'Chandigarh', review:"At this price point the quality is excellent. The PLA is thick enough to hold without any concern. Will buy more.", created_at:'2026-01-29T15:30:00Z', verified_purchase:true },
    { id:'wh007', product_slug:'wall-hook', rating:5, reviewer_name:'Varun Sinha', city:'Noida', review:"White version for my kids' room — they hang their own bags now. The hook is the right height and holds up to schoolbags easily.", created_at:'2026-05-11T11:00:00Z', verified_purchase:true },
    { id:'wh008', product_slug:'wall-hook', rating:5, reviewer_name:'Tanvi Desai', city:'Surat', review:"Minimal design, maximum function. Mounting hardware comes with it which is a nice touch. Overall really impressed.", created_at:'2026-04-30T09:15:00Z', verified_purchase:true },
    { id:'wh009', product_slug:'wall-hook', rating:5, reviewer_name:'Deepak Tiwari', city:'Mumbai', review:"Exactly as described. Clean hook with a minimal profile. Looks designed, not like hardware. Great for modern interiors.", created_at:'2026-03-09T13:00:00Z', verified_purchase:true },
  ],

  'phone-dock': [
    { id:'pd001', product_slug:'phone-dock', rating:5, reviewer_name:'Swati Bajaj', city:'Delhi', review:"Has replaced my old phone stand completely. Cable management is actually thoughtful — the wire routes through the back so you just see the phone. Bedside looks so much cleaner.", created_at:'2026-01-13T10:00:00Z', verified_purchase:true },
    { id:'pd002', product_slug:'phone-dock', rating:5, reviewer_name:'Manish Saxena', city:'Bengaluru', review:"Perfect bedside dock. Phone at the right angle for alarms and checking time. The cable channel works with both USB-C and Lightning cables.", created_at:'2025-12-31T14:30:00Z', verified_purchase:true },
    { id:'pd003', product_slug:'phone-dock', rating:5, reviewer_name:'Ritu Pandey', city:'Pune', review:"The Ivory White version looks clean on my bedside table. Solid and doesn't wobble when I set my phone down in the dark.", created_at:'2026-02-09T09:00:00Z', verified_purchase:true },
    { id:'pd004', product_slug:'phone-dock', rating:4, reviewer_name:'Gaurav Mathur', city:'Jaipur', review:"Good design and practical. The cable management hole could be a bit larger for thicker cable heads. Overall very functional.", created_at:'2026-03-22T11:00:00Z', verified_purchase:true },
    { id:'pd005', product_slug:'phone-dock', rating:5, reviewer_name:'Ankita Chauhan', city:'Ahmedabad', review:"Matte Black version is sleek and minimal. Keeps my phone at a readable angle and the cable stays hidden. Love it.", created_at:'2026-04-07T08:30:00Z', verified_purchase:true },
    { id:'pd006', product_slug:'phone-dock', rating:5, reviewer_name:'Shubham Dixit', city:'Mumbai', review:"I've had several phone stands and this is by far the best looking. The cable routing channel is what sets it apart. Very impressed.", created_at:'2026-01-24T16:00:00Z', verified_purchase:true },
    { id:'pd007', product_slug:'phone-dock', rating:5, reviewer_name:'Pallavi Mishra', city:'Hyderabad', review:"Great gift option. Gifted one to my sister and she loved it. Practical, useful, and looks premium.", created_at:'2026-05-06T12:00:00Z', verified_purchase:true },
    { id:'pd008', product_slug:'phone-dock', rating:5, reviewer_name:'Yash Agrawal', city:'Noida', review:"Perfect bedside companion. The weight is right — not so light it tips, not heavy enough to be annoying.", created_at:'2026-04-24T09:30:00Z', verified_purchase:true },
    { id:'pd009', product_slug:'phone-dock', rating:5, reviewer_name:'Sonal Khanna', city:'Chennai', review:"Clean design and practical function. The cable management is genuinely clever. This is the kind of product TriAkar does really well.", created_at:'2026-03-04T13:30:00Z', verified_purchase:true },
  ],

  'candle-stand': [
    { id:'cs001', product_slug:'candle-stand', rating:5, reviewer_name:'Arjun Sharma', city:'Mumbai', review:"Bought for Diwali decor and it was perfect. The geometric form catches the candlelight beautifully. Stable and holds tea lights securely.", created_at:'2025-12-16T10:00:00Z', verified_purchase:true },
    { id:'cs002', product_slug:'candle-stand', rating:5, reviewer_name:'Priya Mehta', city:'Delhi', review:"Matte Black version is stunning. Looks like art on a shelf even without a candle. Packaging was neat and it arrived in perfect condition.", created_at:'2026-01-04T14:00:00Z', verified_purchase:true },
    { id:'cs003', product_slug:'candle-stand', rating:5, reviewer_name:'Rohan Kapoor', city:'Bengaluru', review:"Great home decor item. The geometric form is very on-trend. Heat-resistant enough for a tea light candle. Beautiful product.", created_at:'2026-02-14T09:30:00Z', verified_purchase:true },
    { id:'cs004', product_slug:'candle-stand', rating:4, reviewer_name:'Sneha Iyer', city:'Hyderabad', review:"Pretty and functional. I'd love a taller version for pillar candles but for tea lights this is perfect. Stone Grey is elegant.", created_at:'2026-03-23T11:00:00Z', verified_purchase:true },
    { id:'cs005', product_slug:'candle-stand', rating:5, reviewer_name:'Vikram Singh', city:'Jaipur', review:"Gifted as a housewarming present. Both the look and the packaging impressed the receiver. Will definitely buy more for gifting.", created_at:'2026-04-09T08:30:00Z', verified_purchase:true },
    { id:'cs006', product_slug:'candle-stand', rating:5, reviewer_name:'Ananya Nair', city:'Kochi', review:"Beautiful piece. Used on my dining table and it adds such warmth. The geometric shape creates interesting shadow patterns when lit.", created_at:'2026-01-21T16:00:00Z', verified_purchase:true },
    { id:'cs007', product_slug:'candle-stand', rating:5, reviewer_name:'Rahul Gupta', city:'Gurugram', review:"Really love this. Simple concept, well executed. It's earned a permanent spot on my coffee table.", created_at:'2026-05-09T11:30:00Z', verified_purchase:true },
    { id:'cs008', product_slug:'candle-stand', rating:5, reviewer_name:'Kavya Reddy', city:'Chennai', review:"The quality is consistent with other TriAkar products. Clean print, good weight, looks great. Matte Black especially is very premium.", created_at:'2026-04-26T10:00:00Z', verified_purchase:true },
    { id:'cs009', product_slug:'candle-stand', rating:5, reviewer_name:'Aditya Kumar', city:'Ahmedabad', review:"Functional and beautiful. Exactly what I was looking for. No wobble, good weight distribution, and the geometric form is timeless.", created_at:'2026-03-03T14:00:00Z', verified_purchase:true },
  ],

  'name-plate': [
    { id:'np001', product_slug:'name-plate', rating:5, reviewer_name:'Pooja Patel', city:'Pune', review:"Ordered a custom name plate for our new apartment and it looks absolutely brilliant on the door. The custom colour matches our door frame perfectly. Excellent communication throughout.", created_at:'2026-01-15T10:00:00Z', verified_purchase:true },
    { id:'np002', product_slug:'name-plate', rating:5, reviewer_name:'Nikhil Joshi', city:'Bengaluru', review:"Gifted to parents for their anniversary as a personalised home gift. They loved it. Clean finish and the letters are sharp and readable. Very professional output.", created_at:'2026-02-06T14:00:00Z', verified_purchase:true },
    { id:'np003', product_slug:'name-plate', rating:5, reviewer_name:'Divya Chaudhary', city:'Delhi', review:"The customization process was smooth. Shared my design preferences and got a proof before printing. Great experience and the result is exactly what I envisioned.", created_at:'2026-03-11T09:30:00Z', verified_purchase:true },
    { id:'np004', product_slug:'name-plate', rating:4, reviewer_name:'Amit Verma', city:'Noida', review:"Good quality name plate. Took a few extra days but the result is worth it. Custom colour was matched perfectly. Would order again.", created_at:'2026-04-01T11:00:00Z', verified_purchase:true },
    { id:'np005', product_slug:'name-plate', rating:5, reviewer_name:'Shreya Malhotra', city:'Mumbai', review:"This is the best home accessory I've bought in a long time. Our door looks so personalised and premium. Highly recommend for housewarming gifts.", created_at:'2026-01-28T08:30:00Z', verified_purchase:true },
    { id:'np006', product_slug:'name-plate', rating:5, reviewer_name:'Karan Bhatia', city:'Chennai', review:"Impressed by the detail in the lettering. Clean edges, smooth finish. The team was responsive and helpful with customization options.", created_at:'2026-05-13T16:00:00Z', verified_purchase:true },
    { id:'np007', product_slug:'name-plate', rating:5, reviewer_name:'Meera Pillai', city:'Hyderabad', review:"Gifted for a housewarming and the family was thrilled. It's a thoughtful, unique gift. The packaging was premium and gift-ready.", created_at:'2026-04-22T12:00:00Z', verified_purchase:true },
    { id:'np008', product_slug:'name-plate', rating:5, reviewer_name:'Siddharth Rao', city:'Ahmedabad', review:"Made for our office cabin door. Looks very professional and the custom colour matched our brand perfectly. Will order more for the whole office.", created_at:'2026-03-16T09:00:00Z', verified_purchase:true },
    { id:'np009', product_slug:'name-plate', rating:5, reviewer_name:'Nisha Agarwal', city:'Jaipur', review:"The craftsmanship is excellent. Letters are crisp, the finish is smooth, and it mounted easily. Perfect for a personalised home touch.", created_at:'2026-02-24T13:30:00Z', verified_purchase:true },
  ],

  'name-letters': [
    { id:'nl001', product_slug:'name-letters', rating:5, reviewer_name:'Varun Sinha', city:'Delhi', review:"Got these for my daughter's room — her name in Ivory White letters on a wooden shelf. They look incredible. The letters are well-weighted and don't tip over easily.", created_at:'2026-01-17T10:00:00Z', verified_purchase:true },
    { id:'nl002', product_slug:'name-letters', rating:5, reviewer_name:'Tanvi Desai', city:'Mumbai', review:"Ordered LOVE for Valentine's Day shelf decor. The Matte Black finish is classy. Great quality at this price point — especially the deal vs MRP.", created_at:'2026-02-11T14:30:00Z', verified_purchase:true },
    { id:'nl003', product_slug:'name-letters', rating:5, reviewer_name:'Deepak Tiwari', city:'Bengaluru', review:"The custom letters arrived packaged individually and in perfect condition. Wood Finish looks incredibly realistic. My desk now has my name in bold — very motivating!", created_at:'2026-03-13T09:00:00Z', verified_purchase:true },
    { id:'nl004', product_slug:'name-letters', rating:4, reviewer_name:'Swati Bajaj', city:'Hyderabad', review:"Really nice letters. Font is clean and modern. One letter had a very slight lean which was easy to adjust. Overall very happy.", created_at:'2026-04-04T11:15:00Z', verified_purchase:true },
    { id:'nl005', product_slug:'name-letters', rating:5, reviewer_name:'Manish Saxena', city:'Jaipur', review:"Gifted for a baby shower with the baby's name. Parents were emotional — it was that thoughtful. The quality and customization made it feel truly special.", created_at:'2026-01-30T08:30:00Z', verified_purchase:true },
    { id:'nl006', product_slug:'name-letters', rating:5, reviewer_name:'Ritu Pandey', city:'Ahmedabad', review:"Stone Grey letters look fantastic on my home office shelf. The printing is consistent across all letters — no variation in quality.", created_at:'2026-05-05T15:00:00Z', verified_purchase:true },
    { id:'nl007', product_slug:'name-letters', rating:5, reviewer_name:'Gaurav Mathur', city:'Noida', review:"The deal is incredible — at ₹499 vs ₹1430 MRP you're getting massive value. And the quality doesn't feel discounted at all. Very impressed.", created_at:'2026-04-17T12:30:00Z', verified_purchase:true },
    { id:'nl008', product_slug:'name-letters', rating:5, reviewer_name:'Ankita Chauhan', city:'Chennai', review:"Freestanding and stable. Placed them on a bookshelf and they've stayed put for months. Love the minimalist font choice.", created_at:'2026-03-28T09:45:00Z', verified_purchase:true },
    { id:'nl009', product_slug:'name-letters', rating:5, reviewer_name:'Shubham Dixit', city:'Kolkata', review:"Custom colour was spot on. The team confirmed before printing and got it exactly right. This is the kind of service that builds trust.", created_at:'2026-02-20T13:00:00Z', verified_purchase:true },
  ],

  'gift-box': [
    { id:'gb001', product_slug:'gift-box', rating:5, reviewer_name:'Pallavi Mishra', city:'Delhi', review:"Ordered for a colleague's farewell and it was the most unique gift anyone gave. The custom 3D-printed items inside were thoughtfully selected. The packaging itself felt premium.", created_at:'2026-01-19T10:00:00Z', verified_purchase:true },
    { id:'gb002', product_slug:'gift-box', rating:5, reviewer_name:'Yash Agrawal', city:'Mumbai', review:"Used TriAkar's gift box for a wedding anniversary. The couple was genuinely touched. Items worked beautifully as a set.", created_at:'2026-02-13T14:00:00Z', verified_purchase:true },
    { id:'gb003', product_slug:'gift-box', rating:5, reviewer_name:'Sonal Khanna', city:'Bengaluru', review:"The best gifting service I've come across. They help you figure out what to include and the final presentation is gorgeous. Will keep using for corporate gifting.", created_at:'2026-03-19T09:30:00Z', verified_purchase:true },
    { id:'gb004', product_slug:'gift-box', rating:4, reviewer_name:'Arjun Sharma', city:'Hyderabad', review:"Great gift box experience. Would love more product options to choose from in future. What's currently there is excellent though.", created_at:'2026-04-03T11:00:00Z', verified_purchase:true },
    { id:'gb005', product_slug:'gift-box', rating:5, reviewer_name:'Priya Mehta', city:'Jaipur', review:"Housewarming gift done right. The recipient was blown away by the thought behind each item. The unboxing experience was beautiful.", created_at:'2026-01-27T08:00:00Z', verified_purchase:true },
    { id:'gb006', product_slug:'gift-box', rating:5, reviewer_name:'Rohan Kapoor', city:'Ahmedabad', review:"Bought for a close friend's big promotion. The customization was meaningful and the quality was impeccable. 10/10 gifting experience.", created_at:'2026-05-15T16:30:00Z', verified_purchase:true },
    { id:'gb007', product_slug:'gift-box', rating:5, reviewer_name:'Sneha Iyer', city:'Pune', review:"TriAkar made the gifting process so easy. Just told them the occasion and recipient and they handled everything. Beautiful result.", created_at:'2026-04-21T12:00:00Z', verified_purchase:true },
    { id:'gb008', product_slug:'gift-box', rating:5, reviewer_name:'Vikram Singh', city:'Chennai', review:"The premium packaging and custom items inside justify the price completely. Everyone who receives this is wowed.", created_at:'2026-03-07T10:00:00Z', verified_purchase:true },
    { id:'gb009', product_slug:'gift-box', rating:5, reviewer_name:'Ananya Nair', city:'Gurugram', review:"Used for 5 corporate gifts. All recipients were impressed. Very helpful team that made the process smooth and consistent across all 5.", created_at:'2026-02-26T13:30:00Z', verified_purchase:true },
  ],

  'bookmark-set': [
    { id:'bm001', product_slug:'bookmark-set', rating:5, reviewer_name:'Rahul Gupta', city:'Delhi', review:"The 4 bookmarks are each slightly different in design which makes them feel curated rather than generic. Great for book lovers. The finishes are smooth.", created_at:'2026-01-06T10:00:00Z', verified_purchase:true },
    { id:'bm002', product_slug:'bookmark-set', rating:5, reviewer_name:'Kavya Reddy', city:'Mumbai', review:"Gifted to my reader aunt and she loved them. Functional and beautiful. The minimal geometric shapes are tasteful.", created_at:'2026-02-02T14:00:00Z', verified_purchase:true },
    { id:'bm003', product_slug:'bookmark-set', rating:5, reviewer_name:'Aditya Kumar', city:'Bengaluru', review:"Solid little gifts. At this price point you can bundle them with something else for a thoughtful gift set. Quality is great.", created_at:'2025-12-27T09:00:00Z', verified_purchase:true },
    { id:'bm004', product_slug:'bookmark-set', rating:4, reviewer_name:'Pooja Patel', city:'Hyderabad', review:"Nice set. Would love the option to choose specific designs within the set. The ones I received were all good though.", created_at:'2026-03-21T11:00:00Z', verified_purchase:true },
    { id:'bm005', product_slug:'bookmark-set', rating:5, reviewer_name:'Nikhil Joshi', city:'Jaipur', review:"Perfect gift for book lovers. Clean minimal designs that work with any aesthetic.", created_at:'2026-04-12T08:30:00Z', verified_purchase:true },
    { id:'bm006', product_slug:'bookmark-set', rating:5, reviewer_name:'Divya Chaudhary', city:'Chandigarh', review:"The assorted finish is really well selected. Each one is distinct. Love using different ones for different books.", created_at:'2026-01-22T16:00:00Z', verified_purchase:true },
    { id:'bm007', product_slug:'bookmark-set', rating:5, reviewer_name:'Amit Verma', city:'Pune', review:"Good weight — stays in the book properly, doesn't fall out. The design is minimal which I love. Good purchase.", created_at:'2026-05-04T12:00:00Z', verified_purchase:true },
    { id:'bm008', product_slug:'bookmark-set', rating:5, reviewer_name:'Shreya Malhotra', city:'Ahmedabad', review:"Unique and practical. Gave as a teacher's gift and got a very positive response. The packaging was neat.", created_at:'2026-04-16T09:00:00Z', verified_purchase:true },
    { id:'bm009', product_slug:'bookmark-set', rating:5, reviewer_name:'Karan Bhatia', city:'Kolkata', review:"These are the nicest bookmarks I've ever seen. The 3D printed material is light but doesn't feel flimsy. Love them.", created_at:'2026-03-02T13:00:00Z', verified_purchase:true },
  ],

  'coaster-set': [
    { id:'co001', product_slug:'coaster-set', rating:5, reviewer_name:'Meera Pillai', city:'Kochi', review:"Exactly the coasters I was looking for. Geometric, minimal, and functional. They protect the table and look intentional while doing so.", created_at:'2026-01-18T10:00:00Z', verified_purchase:true },
    { id:'co002', product_slug:'coaster-set', rating:5, reviewer_name:'Siddharth Rao', city:'Delhi', review:"Matte Black coasters on a light wooden table look absolutely stunning. The geometric pattern is subtle and elegant.", created_at:'2026-02-04T14:30:00Z', verified_purchase:true },
    { id:'co003', product_slug:'coaster-set', rating:5, reviewer_name:'Nisha Agarwal', city:'Mumbai', review:"Bought for home and everyone who visits asks where I got them. The answer is always TriAkar. They're conversation starters.", created_at:'2026-03-12T09:00:00Z', verified_purchase:true },
    { id:'co004', product_slug:'coaster-set', rating:4, reviewer_name:'Varun Sinha', city:'Bengaluru', review:"Great coasters. A felt backing option would be nice to avoid any chance of sliding. As is they work well on most surfaces.", created_at:'2026-04-05T11:00:00Z', verified_purchase:true },
    { id:'co005', product_slug:'coaster-set', rating:5, reviewer_name:'Tanvi Desai', city:'Hyderabad', review:"Gifted for a housewarming along with the Facet Vase — the combo was stunning. Both are beautiful TriAkar products.", created_at:'2026-01-31T08:30:00Z', verified_purchase:true },
    { id:'co006', product_slug:'coaster-set', rating:5, reviewer_name:'Deepak Tiwari', city:'Jaipur', review:"Stone Grey set blends with my neutral home decor perfectly. The print quality is consistent across all 4 coasters.", created_at:'2026-05-14T16:00:00Z', verified_purchase:true },
    { id:'co007', product_slug:'coaster-set', rating:5, reviewer_name:'Swati Bajaj', city:'Chandigarh', review:"These have replaced my boring cork coasters completely. So much more elegant and they're holding up great after daily use.", created_at:'2026-04-27T12:00:00Z', verified_purchase:true },
    { id:'co008', product_slug:'coaster-set', rating:5, reviewer_name:'Manish Saxena', city:'Ahmedabad', review:"Great value for the set. Practical and beautiful. The White coasters especially look pristine. Very satisfied.", created_at:'2026-03-06T10:00:00Z', verified_purchase:true },
    { id:'co009', product_slug:'coaster-set', rating:5, reviewer_name:'Ritu Pandey', city:'Kolkata', review:"The geometry on these is sharp and clean. No rough edges. Very happy with the finish and they work great as coasters.", created_at:'2026-02-22T13:30:00Z', verified_purchase:true },
  ],

  'mini-keychain': [
    { id:'mk001', product_slug:'mini-keychain', rating:5, reviewer_name:'Gaurav Mathur', city:'Delhi', review:"Super cute and minimal. The geometric design is small but detailed. Great little gift. I ordered 5 for friends and they all loved it.", created_at:'2026-01-08T10:00:00Z', verified_purchase:true },
    { id:'mk002', product_slug:'mini-keychain', rating:5, reviewer_name:'Ankita Chauhan', city:'Mumbai', review:"At ₹119 this is a steal. The finish is smooth, the keyring attachment is solid. No complaints at all.", created_at:'2025-12-23T14:00:00Z', verified_purchase:true },
    { id:'mk003', product_slug:'mini-keychain', rating:5, reviewer_name:'Shubham Dixit', city:'Bengaluru', review:"Ordered in custom colour to match my bag. Came out perfectly. Such a tiny thing but it adds personality to my keys.", created_at:'2026-02-16T09:30:00Z', verified_purchase:true },
    { id:'mk004', product_slug:'mini-keychain', rating:4, reviewer_name:'Pallavi Mishra', city:'Hyderabad', review:"Cute little keychain. The loop size is standard — works with most keyrings. Would love a slightly larger version too.", created_at:'2026-03-26T11:00:00Z', verified_purchase:true },
    { id:'mk005', product_slug:'mini-keychain', rating:5, reviewer_name:'Yash Agrawal', city:'Jaipur', review:"Bought 10 as party favors for a small birthday gathering. Everyone was impressed by the quality for the price. Great idea.", created_at:'2026-04-14T08:30:00Z', verified_purchase:true },
    { id:'mk006', product_slug:'mini-keychain', rating:5, reviewer_name:'Sonal Khanna', city:'Pune', review:"The weight is right — not too heavy. The geometric design is understated and tasteful. Love it on my keys.", created_at:'2026-01-23T16:00:00Z', verified_purchase:true },
    { id:'mk007', product_slug:'mini-keychain', rating:5, reviewer_name:'Arjun Sharma', city:'Chandigarh', review:"Super value for money. Quality matches products 3x the price. TriAkar really doesn't compromise even at this price.", created_at:'2026-05-10T12:00:00Z', verified_purchase:true },
    { id:'mk008', product_slug:'mini-keychain', rating:5, reviewer_name:'Priya Mehta', city:'Ahmedabad', review:"Gifted to my nephew for his birthday. He uses it on his school bag. Sturdy little thing. Very good gift.", created_at:'2026-04-23T09:30:00Z', verified_purchase:true },
    { id:'mk009', product_slug:'mini-keychain', rating:5, reviewer_name:'Rohan Kapoor', city:'Kolkata', review:"Perfect for bulk gifting or just a personal treat. The customization option makes it special.", created_at:'2026-03-10T13:00:00Z', verified_purchase:true },
  ],

  'custom-bracket': [
    { id:'cb001', product_slug:'custom-bracket', rating:5, reviewer_name:'Sneha Iyer', city:'Chennai', review:"Came to TriAkar with a broken chair arm part and they delivered an exact match in 3 days. Material and colour matched the original. Saved me from buying a whole new chair.", created_at:'2026-01-20T10:00:00Z', verified_purchase:true },
    { id:'cb002', product_slug:'custom-bracket', rating:5, reviewer_name:'Vikram Singh', city:'Delhi', review:"Incredible service. Sent photos of the broken part and they reverse-engineered and printed it. Fit perfectly. Much cheaper than ordering from the manufacturer.", created_at:'2026-02-08T14:00:00Z', verified_purchase:true },
    { id:'cb003', product_slug:'custom-bracket', rating:5, reviewer_name:'Ananya Nair', city:'Bengaluru', review:"Used for a dishwasher rack part. The team figured out the right material and dimensions from my photos and description. Result was perfect. Very professional service.", created_at:'2026-03-14T09:00:00Z', verified_purchase:true },
    { id:'cb004', product_slug:'custom-bracket', rating:4, reviewer_name:'Rahul Gupta', city:'Hyderabad', review:"Good service. Communication was clear. Took a day longer than expected but the final part fit well. Will use again for future repairs.", created_at:'2026-04-02T11:00:00Z', verified_purchase:true },
    { id:'cb005', product_slug:'custom-bracket', rating:5, reviewer_name:'Kavya Reddy', city:'Mumbai', review:"The best replacement part service available in India. Fast, affordable, and accurate. The matched colour is genuinely impressive.", created_at:'2026-01-29T08:30:00Z', verified_purchase:true },
    { id:'cb006', product_slug:'custom-bracket', rating:5, reviewer_name:'Aditya Kumar', city:'Jaipur', review:"Ordered a custom bracket for a broken blind mechanism. Works perfectly. The 3D printing quality is solid — no flexing or breaking.", created_at:'2026-05-08T16:00:00Z', verified_purchase:true },
    { id:'cb007', product_slug:'custom-bracket', rating:5, reviewer_name:'Pooja Patel', city:'Ahmedabad', review:"Such a smart service. The part would have cost ₹3,000 from the original brand. Got it printed for ₹299. TriAkar is genuinely solving a real problem.", created_at:'2026-04-19T12:00:00Z', verified_purchase:true },
    { id:'cb008', product_slug:'custom-bracket', rating:5, reviewer_name:'Nikhil Joshi', city:'Noida', review:"The whole process was seamless. WhatsApp photos, quick quote, fast printing. My broken bracket is now as good as new.", created_at:'2026-03-05T10:00:00Z', verified_purchase:true },
    { id:'cb009', product_slug:'custom-bracket', rating:5, reviewer_name:'Divya Chaudhary', city:'Gurugram', review:"Replaced a complicated shelf pin that wasn't available anywhere. TriAkar nailed it. The part has been in use for 2 months and is holding up well.", created_at:'2026-02-19T13:30:00Z', verified_purchase:true },
  ],

  'prototype': [
    { id:'pr001', product_slug:'prototype', rating:5, reviewer_name:'Amit Verma', city:'Delhi', review:"Used TriAkar for my product prototype and they delivered exactly what I needed. Quick turnaround, clear communication, and print quality was very good for prototype purposes.", created_at:'2026-01-21T10:00:00Z', verified_purchase:true },
    { id:'pr002', product_slug:'prototype', rating:5, reviewer_name:'Shreya Malhotra', city:'Bengaluru', review:"First time prototyping a product idea and TriAkar made it easy. They advised on design adjustments for printability and the result was usable on the first try.", created_at:'2026-02-10T14:00:00Z', verified_purchase:true },
    { id:'pr003', product_slug:'prototype', rating:5, reviewer_name:'Karan Bhatia', city:'Mumbai', review:"Rapid prototyping that's actually rapid. 48-hour turnaround for my startup's first physical product concept. The team was helpful and knowledgeable.", created_at:'2026-03-16T09:00:00Z', verified_purchase:true },
    { id:'pr004', product_slug:'prototype', rating:4, reviewer_name:'Meera Pillai', city:'Hyderabad', review:"Good service for prototyping. I needed two iterations to get the fit right but both were affordable and the team was patient. Would use again.", created_at:'2026-04-06T11:00:00Z', verified_purchase:true },
    { id:'pr005', product_slug:'prototype', rating:5, reviewer_name:'Siddharth Rao', city:'Jaipur', review:"TriAkar is my go-to for prototyping ideas before committing to expensive tooling. Material options and accuracy are great for proof-of-concept work.", created_at:'2026-01-27T08:30:00Z', verified_purchase:true },
    { id:'pr006', product_slug:'prototype', rating:5, reviewer_name:'Nisha Agarwal', city:'Pune', review:"Needed a functional prototype for a pitch and they delivered on time. Quality was good enough to demo to investors. Very impressed.", created_at:'2026-05-13T16:00:00Z', verified_purchase:true },
    { id:'pr007', product_slug:'prototype', rating:5, reviewer_name:'Varun Sinha', city:'Ahmedabad', review:"The best value prototyping service I've used. Professional, fast, and reasonably priced. The prints are clean and functional.", created_at:'2026-04-24T12:00:00Z', verified_purchase:true },
    { id:'pr008', product_slug:'prototype', rating:5, reviewer_name:'Tanvi Desai', city:'Noida', review:"Used for a college project prototype. The quality was far better than my desktop printer. Team was helpful in optimising the model for printing.", created_at:'2026-03-08T10:00:00Z', verified_purchase:true },
    { id:'pr009', product_slug:'prototype', rating:5, reviewer_name:'Deepak Tiwari', city:'Chennai', review:"Reliable and professional. The prints are accurate to my CAD model. This is the kind of service that helps ideas become real.", created_at:'2026-02-23T13:30:00Z', verified_purchase:true },
  ],

  'bulk-gifting': [
    { id:'bg001', product_slug:'bulk-gifting', rating:5, reviewer_name:'Swati Bajaj', city:'Delhi', review:"Ordered 25 custom items for our company's annual day. Every single piece was consistent in quality and the custom branding looked professional. TriAkar handled the whole process smoothly.", created_at:'2026-01-22T10:00:00Z', verified_purchase:true },
    { id:'bg002', product_slug:'bulk-gifting', rating:5, reviewer_name:'Manish Saxena', city:'Mumbai', review:"Corporate gifting done right. 40 custom pieces with our logo. Delivered on time and packaged beautifully. Our clients were very impressed by the uniqueness.", created_at:'2026-02-12T14:00:00Z', verified_purchase:true },
    { id:'bg003', product_slug:'bulk-gifting', rating:5, reviewer_name:'Ritu Pandey', city:'Bengaluru', review:"Used TriAkar for a client appreciation event. 50 pieces and every one was perfect. Custom colour and branding were spot on. Will use again next quarter.", created_at:'2026-03-18T09:00:00Z', verified_purchase:true },
    { id:'bg004', product_slug:'bulk-gifting', rating:4, reviewer_name:'Gaurav Mathur', city:'Hyderabad', review:"Good bulk order experience. Slight delay in first consignment but quality was excellent. Branding accuracy was perfect.", created_at:'2026-04-07T11:00:00Z', verified_purchase:true },
    { id:'bg005', product_slug:'bulk-gifting', rating:5, reviewer_name:'Ankita Chauhan', city:'Jaipur', review:"Ordered Diwali gifts for our team of 30. Custom colours and each piece was wrapped individually. Made the gifting ceremony feel special.", created_at:'2025-12-19T08:30:00Z', verified_purchase:true },
    { id:'bg006', product_slug:'bulk-gifting', rating:5, reviewer_name:'Shubham Dixit', city:'Pune', review:"The best corporate gifting decision we made this year. Our partners remember us because of those unique gifts. Planning a larger order next year.", created_at:'2026-05-16T16:00:00Z', verified_purchase:true },
    { id:'bg007', product_slug:'bulk-gifting', rating:5, reviewer_name:'Pallavi Mishra', city:'Ahmedabad', review:"TriAkar made corporate gifting feel genuinely thoughtful rather than generic. The 3D printed items with our branding looked premium and unique.", created_at:'2026-04-29T12:00:00Z', verified_purchase:true },
    { id:'bg008', product_slug:'bulk-gifting', rating:5, reviewer_name:'Yash Agrawal', city:'Noida', review:"Very professional bulk order handling. The team communicated proactively at every stage. Quality was consistent across all 60 pieces.", created_at:'2026-03-24T10:00:00Z', verified_purchase:true },
    { id:'bg009', product_slug:'bulk-gifting', rating:5, reviewer_name:'Sonal Khanna', city:'Gurugram', review:"Highly recommend for corporate gifting. The minimum order of 10 is very accessible and per-piece pricing is very competitive for the quality.", created_at:'2026-02-27T13:30:00Z', verified_purchase:true },
  ],

};

/* ── Precomputed stats per product (score + count) for product cards ── */
var REVIEW_STATS = {};
(function() {
  var slugs = Object.keys(REVIEWS_DATA);
  for (var i = 0; i < slugs.length; i++) {
    var slug = slugs[i];
    var revs = REVIEWS_DATA[slug];
    if (!revs || !revs.length) continue;
    var sum = 0;
    for (var j = 0; j < revs.length; j++) sum += Number(revs[j].rating) || 0;
    var avg = sum / revs.length;
    REVIEW_STATS[slug] = { score: Math.round(avg * 10) / 10, count: revs.length };
  }
})();

if (typeof window !== 'undefined') {
  window.REVIEWS_DATA = REVIEWS_DATA;
  window.REVIEW_STATS = REVIEW_STATS;
}
