-- TriAkar — Stories CMS: replace placeholder/sample content with finalized stories
--
-- The 12 seed stories inserted by 20260710_site_stories.sql were always placeholder/sample
-- content (Rajesh's Maruti bracket, the Jaipur wedding ring holders, etc). This replaces them
-- wholesale with 21 real, finalized customer stories supplied by the user, October 2025
-- through August 2026.
--
-- Notes on mapping from the source data to this schema:
--   - Source category "Replacement Parts" (plural) is stored as tag "Replacement Part"
--     (singular) to match the existing filter pill wiring in stories.html
--     (data-filter="Replacement Part"); the pill label itself already displays "REPLACEMENT
--     PARTS" in the UI, so this is a storage/display split that already existed, not a new one.
--   - Source only provided one block of story text ("hook"), not a separate short teaser vs
--     full detail, so it is stored verbatim in both excerpt and full_text rather than being
--     shortened or paraphrased.
--   - Source "customer" field is stored as-is in customer_name, including the literal
--     "Name withheld, customer hasn't approved sharing it yet" placeholder text, so it renders
--     unaltered. customer_location is left null for all rows since the source did not separate
--     name from location.
--   - image_url is left null for every row (no images supplied yet); the existing card
--     fallback (tag emoji icon) covers this without breaking layout.
--   - Where more than one story shares a year+month, sort_order preserves the order the
--     stories appeared in the source file.
--
-- Safe to run once in the Supabase SQL Editor. Idempotent via full delete + reinsert.

DELETE FROM site_stories;

INSERT INTO site_stories (year, month, sort_order, tag, title, excerpt, full_text, customer_name, slug, published) VALUES
(2026, 8, 1, 'Prototype', 'Payment to delivery in 35 minutes flat', 'Our fastest order ever, 25 minutes from payment to dispatch, delivered in another 10 minutes via Porter. A perfect quality mechanical part for his AI robotics project. His reaction: this is a different kind of fast.', 'Our fastest order ever, 25 minutes from payment to dispatch, delivered in another 10 minutes via Porter. A perfect quality mechanical part for his AI robotics project. His reaction: this is a different kind of fast.', 'An AI robotics innovator', 'payment-to-delivery-in-35-minutes-flat', true),
(2026, 8, 2, 'Gifting', 'A dog statue so real, she couldn''t stop staring', 'She wanted a statue of her friend''s old dog. Monsoon rain kept slowing the drying, but we finished it in 17 days. She said it looked more real than she expected.', 'She wanted a statue of her friend''s old dog. Monsoon rain kept slowing the drying, but we finished it in 17 days. She said it looked more real than she expected.', 'Palak P.', 'a-dog-statue-so-real-she-couldnt-stop-staring', true),
(2026, 7, 1, 'Prototype', '10 DRDO enclosure boxes, designed and built in 48 hours', 'He needed 10 fully usable enclosure boxes for a DRDO project, ready fast. We designed and completed the entire set in just 48 hours, working through day and night without noticing the difference.', 'He needed 10 fully usable enclosure boxes for a DRDO project, ready fast. We designed and completed the entire set in just 48 hours, working through day and night without noticing the difference.', 'Tej G.', '10-drdo-enclosure-boxes-designed-and-built-in-48-hours', true),
(2026, 7, 2, 'Gifting', 'A Batman holding up his GPU, sized to the millimeter', 'He wanted his new PC build to look like Batman was lifting the graphics card, fit into a tight cabinet space. We visited his home to take exact measurements and delivered it in a week.', 'He wanted his new PC build to look like Batman was lifting the graphics card, fit into a tight cabinet space. We visited his home to take exact measurements and delivered it in a week.', 'Suparn', 'a-batman-holding-up-his-gpu-sized-to-the-millimeter', true),
(2026, 6, 1, 'Gifting', 'A custom puzzle, and a lesson in keeping our word', 'This was the first time we missed a promised delivery date. Mr. Divesh understood the situation, and even with the delay, gave us honest, positive feedback. It taught us something we needed to learn.', 'This was the first time we missed a promised delivery date. Mr. Divesh understood the situation, and even with the delay, gave us honest, positive feedback. It taught us something we needed to learn.', 'Divesh', 'a-custom-puzzle-and-a-lesson-in-keeping-our-word', true),
(2026, 6, 2, 'Prototype', 'A neuron model, built from a school project file', 'A student needed a neuron model for a school project. We took the file they gave us, fixed a few issues in the design, and built it to match exactly what the project needed.', 'A student needed a neuron model for a school project. We took the file they gave us, fixed a few issues in the design, and built it to match exactly what the project needed.', 'A young science student', 'a-neuron-model-built-from-a-school-project-file', true),
(2026, 6, 3, 'Gifting', 'A family name tree for a new home, delivered in 72 hours', 'For a griha pravesh, she sent us an AI-generated idea of a tree with every family member''s name on it. We turned it into a real piece and delivered it in three days.', 'For a griha pravesh, she sent us an AI-generated idea of a tree with every family member''s name on it. We turned it into a real piece and delivered it in three days.', 'Daisy', 'a-family-name-tree-for-a-new-home-delivered-in-72-hours', true),
(2026, 5, 1, 'Gifting', 'A silver fish that needed a box to stop tarnishing', 'His hand-detailed Japanese-style silver fish kept oxidizing and needed constant cleaning. We built a box to slow that down, with a marble-finish turtle stand to hold the fish. He kept coming back with new ideas before the order was even done.', 'His hand-detailed Japanese-style silver fish kept oxidizing and needed constant cleaning. We built a box to slow that down, with a marble-finish turtle stand to hold the fish. He kept coming back with new ideas before the order was even done.', 'Abhishek G.', 'a-silver-fish-that-needed-a-box-to-stop-tarnishing', true),
(2026, 5, 2, 'Gifting', 'A gift with the wrong name, fixed in 72 hours', 'He loved a gift he''d received, except his child''s name was printed wrong on it. He had no idea how to fix it until a friend pointed him to us. What we delivered surprised him completely, done in 72 hours.', 'He loved a gift he''d received, except his child''s name was printed wrong on it. He had no idea how to fix it until a friend pointed him to us. What we delivered surprised him completely, done in 72 hours.', 'Himanshu S.', 'a-gift-with-the-wrong-name-fixed-in-72-hours', true),
(2026, 5, 3, 'Gifting', '40 personalised keychains for a 40th birthday, every message different', 'For her 40th birthday, she wanted to thank 40 people, colleagues, friends and family who''ve been there for her. Each keychain carried a message written just for that person, straight from the heart. It took us 24 days to get every one right. Her review: more effort than she thought anyone would put in.', 'For her 40th birthday, she wanted to thank 40 people, colleagues, friends and family who''ve been there for her. Each keychain carried a message written just for that person, straight from the heart. It took us 24 days to get every one right. Her review: more effort than she thought anyone would put in.', 'Neha', '40-personalised-keychains-for-a-40th-birthday-every-message-different', true),
(2026, 4, 1, 'Prototype', '8 design changes, 13 days, one working enclosure', 'He needed to prototype a login device fast, with changes coming in almost daily. We pushed through 8 revisions in 13 days and delivered 4 finished enclosure parts, taking his design from idea to real object.', 'He needed to prototype a login device fast, with changes coming in almost daily. We pushed through 8 revisions in 13 days and delivered 4 finished enclosure parts, taking his design from idea to real object.', 'Tej G.', '8-design-changes-13-days-one-working-enclosure', true),
(2026, 3, 1, 'Gifting', 'A cute custom stand for his special friend, made from his own idea', 'He wanted to gift his friend a customized stand, made just for her. He shared images, ideas and her name, and we put it all together into one perfect piece. He was happy with the work, she was happy with his choice.', 'He wanted to gift his friend a customized stand, made just for her. He shared images, ideas and her name, and we put it all together into one perfect piece. He was happy with the work, she was happy with his choice.', 'Tushar', 'a-cute-custom-stand-for-his-special-friend-made-from-his-own-idea', true),
(2026, 3, 2, 'Gifting', 'A Netflix-style gift that became a catalogue product', 'Our returning client Chanda wanted something special for her best friend''s engagement. She sent us the idea, a personalised Netflix-style poster, and we brought it to life. She loved it so much it''s now part of our regular catalogue.', 'Our returning client Chanda wanted something special for her best friend''s engagement. She sent us the idea, a personalised Netflix-style poster, and we brought it to life. She loved it so much it''s now part of our regular catalogue.', 'Chanda', 'a-netflix-style-gift-that-became-a-catalogue-product', true),
(2026, 2, 1, 'Gifting', 'A photo frame for her brother''s 51st birthday', 'She wanted something personal for her brother''s big day. She sent us a photo and a quote idea, and we turned it into a custom photo frame made just for him.', 'She wanted something personal for her brother''s big day. She sent us a photo and a quote idea, and we turned it into a custom photo frame made just for him.', 'Hema B.', 'a-photo-frame-for-her-brothers-51st-birthday', true),
(2026, 1, 1, 'Gifting', 'A nameplate exactly the way he imagined it', 'He had a clear vision for a nameplate that would match his home''s look. We built it exactly as he pictured, in just a week.', 'He had a clear vision for a nameplate that would match his home''s look. We built it exactly as he pictured, in just a week.', 'Abhay S.', 'a-nameplate-exactly-the-way-he-imagined-it', true),
(2025, 12, 1, 'Replacement Part', 'A 9,000 rupee car part, replaced with one tiny 3D print', 'His old Skoda''s window up-down button had a broken part, no bigger than a fingernail, around 2mm by 4mm by 2mm. Instead of paying 9,000 rupees for a new one, he sent us the piece and we printed a replacement. His words, it works better than new.', 'His old Skoda''s window up-down button had a broken part, no bigger than a fingernail, around 2mm by 4mm by 2mm. Instead of paying 9,000 rupees for a new one, he sent us the piece and we printed a replacement. His words, it works better than new.', 'Ankush K.', 'a-9-000-rupee-car-part-replaced-with-one-tiny-3d-print', true),
(2026, 6, 4, 'Gifting', 'A Krishna figurine detailed enough for resin art', 'She needed a Krishna figurine with a level of detail she couldn''t find anywhere else, for her resin work. It took 8 reprints to get it right, finished in 4 days. She loved it so much, she''s now one of our regulars.', 'She needed a Krishna figurine with a level of detail she couldn''t find anywhere else, for her resin work. It took 8 reprints to get it right, finished in 4 days. She loved it so much, she''s now one of our regulars.', 'Shampi', 'a-krishna-figurine-detailed-enough-for-resin-art', true),
(2026, 6, 5, 'Corporate', '200 pieces, 4 days, zero delays', 'Plane Pockets needed 200 weight machines custom branded with their name, gift packed and dispatched to Mumbai, all in just 4 days. Dispatch was done fast, with tight coordination on both sides.', 'Plane Pockets needed 200 weight machines custom branded with their name, gift packed and dispatched to Mumbai, all in just 4 days. Dispatch was done fast, with tight coordination on both sides.', 'Plane Pockets', '200-pieces-4-days-zero-delays', true),
(2025, 10, 1, 'Corporate', 'Our first bulk lamp order, delivered just before Diwali', 'Our very first bulk order of Miami lamps, in different colours and shades, each with 3 changing light modes. We got the entire order delivered on time, right before Diwali.', 'Our very first bulk order of Miami lamps, in different colours and shades, each with 3 changing light modes. We got the entire order delivered on time, right before Diwali.', 'Sanjula V.', 'our-first-bulk-lamp-order-delivered-just-before-diwali', true),
(2025, 11, 1, 'Gifting', 'A golden Ganesh ji with the bride and groom''s initials, for the whole baraat', 'For a wedding, the bride''s family wanted a bulk gift for the groom''s side, a golden finish Ganesh ji with both families'' initials on it. We completed the entire order in 18 days.', 'For a wedding, the bride''s family wanted a bulk gift for the groom''s side, a golden finish Ganesh ji with both families'' initials on it. We completed the entire order in 18 days.', 'Name withheld, customer hasn''t approved sharing it yet', 'a-golden-ganesh-ji-with-the-bride-and-grooms-initials-for-the-whole-baraat', true),
(2025, 11, 2, 'Gifting', 'He knew every little thing she loved, we just brought it to life', 'He knew her favourite characters, her colours, the little things she loved most. He just needed someone to turn all that into something real. We built it with him, and it helped turn a good friendship into something more.', 'He knew her favourite characters, her colours, the little things she loved most. He just needed someone to turn all that into something real. We built it with him, and it helped turn a good friendship into something more.', 'Teja V.', 'he-knew-every-little-thing-she-loved-we-just-brought-it-to-life', true);
