-- Follow-up correction to 20260723_record_id_extension_and_hardening.sql.
--
-- That migration's REVOKE ... FROM PUBLIC turned out to be a no-op against Supabase's
-- actual access model: Supabase auto-grants EXECUTE on new functions directly to the
-- anon and authenticated roles at creation time, separate from the PUBLIC pseudo-role,
-- so revoking only FROM PUBLIC left anon (fully unauthenticated) able to call all four
-- SECURITY DEFINER functions. Verified live via an anon-key RPC call before this ran
-- (HTTP 200, a real record ID was generated by an anonymous client).
--
-- This migration is the authoritative statement of the intended final state:
--   - anon (unauthenticated): no execute, these functions are never meant to be
--     callable without a logged-in session.
--   - authenticated: execute allowed, the app's own logged-in admin flows
--     (Add Order, Quotations, Recycle Bin purge) call these directly as the
--     logged-in user, not through the backend service role.
--
-- Already applied by hand in the Supabase SQL Editor on 2026-07-24 (re-verified: anon
-- calls to all four now return 42501 permission denied, authenticated calls still work).
-- This file just brings the tracked migration history in sync with that live state;
-- every statement below is idempotent, safe to run again.
--
-- Safe, additive. Run once in Supabase SQL Editor (harmless if already applied by hand).
-- ════════════════════════════════════════════════════════════════════════════════

REVOKE EXECUTE ON FUNCTION gen_record_id(TEXT, TEXT)            FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION purge_old_recycle_bin()              FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION biz_next_quotation_number(TEXT)      FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION biz_next_invoice_number(TEXT)        FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION gen_record_id(TEXT, TEXT)             TO authenticated;
GRANT EXECUTE ON FUNCTION purge_old_recycle_bin()               TO authenticated;
GRANT EXECUTE ON FUNCTION biz_next_quotation_number(TEXT)       TO authenticated;
GRANT EXECUTE ON FUNCTION biz_next_invoice_number(TEXT)         TO authenticated;

INSERT INTO schema_migrations (filename) VALUES
  ('20260724_anon_execute_hardening_fix.sql')
ON CONFLICT (filename) DO NOTHING;

-- ── VERIFY ───────────────────────────────────────────────────────────────────────
-- SELECT proname, proacl FROM pg_proc WHERE proname IN
--   ('gen_record_id','purge_old_recycle_bin','biz_next_quotation_number','biz_next_invoice_number');
--   (proacl should show execute for authenticated and NOT for anon/PUBLIC/"=X")
--
-- Anon should be blocked (expect 42501 permission denied):
--   curl -X POST '<SUPA_URL>/rest/v1/rpc/gen_record_id' \
--     -H "apikey: <anon key>" -H "Authorization: Bearer <anon key>" \
--     -H "Content-Type: application/json" -d '{"p_entity_type":"order"}'
-- ════════════════════════════════════════════════════════════════════════════════
